<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Email', 'erp');

/**
 * BaseEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_email
 * @property string $assunto
 * @property string $descricao
 * @property integer $numero_os
 * @property integer $vod_cliente
 * @property integer $cod_veiculo
 * @property Veiculo $Veiculo
 * @property Clientes $Clientes
 * 
 * @method integer  getCodEmail()    Returns the current record's "cod_email" value
 * @method string   getAssunto()     Returns the current record's "assunto" value
 * @method string   getDescricao()   Returns the current record's "descricao" value
 * @method integer  getNumeroOs()    Returns the current record's "numero_os" value
 * @method integer  getVodCliente()  Returns the current record's "vod_cliente" value
 * @method integer  getCodVeiculo()  Returns the current record's "cod_veiculo" value
 * @method Veiculo  getVeiculo()     Returns the current record's "Veiculo" value
 * @method Clientes getClientes()    Returns the current record's "Clientes" value
 * @method Email    setCodEmail()    Sets the current record's "cod_email" value
 * @method Email    setAssunto()     Sets the current record's "assunto" value
 * @method Email    setDescricao()   Sets the current record's "descricao" value
 * @method Email    setNumeroOs()    Sets the current record's "numero_os" value
 * @method Email    setVodCliente()  Sets the current record's "vod_cliente" value
 * @method Email    setCodVeiculo()  Sets the current record's "cod_veiculo" value
 * @method Email    setVeiculo()     Sets the current record's "Veiculo" value
 * @method Email    setClientes()    Sets the current record's "Clientes" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email');
        $this->hasColumn('cod_email', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('assunto', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('descricao', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('numero_os', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vod_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cod_veiculo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Veiculo', array(
             'local' => 'cod_veiculo',
             'foreign' => 'cod_veiculo'));

        $this->hasOne('Clientes', array(
             'local' => 'vod_cliente',
             'foreign' => 'cod_clientes'));
    }
}