<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mensagem', 'bd');

/**
 * BaseMensagem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmensagem
 * @property integer $cod_conversa
 * @property string $conversa
 * @property date $data_cadastro
 * @property string $detalhe_orcamento
 * @property integer $cod_usuario
 * @property integer $cod_imagem
 * @property Imagens $Imagens
 * 
 * @method integer  getIdmensagem()        Returns the current record's "idmensagem" value
 * @method integer  getCodConversa()       Returns the current record's "cod_conversa" value
 * @method string   getConversa()          Returns the current record's "conversa" value
 * @method date     getDataCadastro()      Returns the current record's "data_cadastro" value
 * @method string   getDetalheOrcamento()  Returns the current record's "detalhe_orcamento" value
 * @method integer  getCodUsuario()        Returns the current record's "cod_usuario" value
 * @method integer  getCodImagem()         Returns the current record's "cod_imagem" value
 * @method Imagens  getImagens()           Returns the current record's "Imagens" value
 * @method Mensagem setIdmensagem()        Sets the current record's "idmensagem" value
 * @method Mensagem setCodConversa()       Sets the current record's "cod_conversa" value
 * @method Mensagem setConversa()          Sets the current record's "conversa" value
 * @method Mensagem setDataCadastro()      Sets the current record's "data_cadastro" value
 * @method Mensagem setDetalheOrcamento()  Sets the current record's "detalhe_orcamento" value
 * @method Mensagem setCodUsuario()        Sets the current record's "cod_usuario" value
 * @method Mensagem setCodImagem()         Sets the current record's "cod_imagem" value
 * @method Mensagem setImagens()           Sets the current record's "Imagens" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensagem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensagem');
        $this->hasColumn('idmensagem', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cod_conversa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('conversa', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('data_cadastro', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('detalhe_orcamento', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cod_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cod_imagem', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Imagens', array(
             'local' => 'cod_imagem',
             'foreign' => 'idimagens'));
    }
}