<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Erps', 'erp');

/**
 * BaseErps
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_erps
 * @property string $nome
 * @property string $rg
 * @property string $cpf
 * @property string $email
 * @property string $status
 * @property string $estado
 * @property string $cidade
 * @property string $rua
 * @property string $numero
 * @property string $bairro
 * @property string $cep
 * @property string $complemento
 * 
 * @method integer getCodErps()     Returns the current record's "cod_erps" value
 * @method string  getNome()        Returns the current record's "nome" value
 * @method string  getRg()          Returns the current record's "rg" value
 * @method string  getCpf()         Returns the current record's "cpf" value
 * @method string  getEmail()       Returns the current record's "email" value
 * @method string  getStatus()      Returns the current record's "status" value
 * @method string  getEstado()      Returns the current record's "estado" value
 * @method string  getCidade()      Returns the current record's "cidade" value
 * @method string  getRua()         Returns the current record's "rua" value
 * @method string  getNumero()      Returns the current record's "numero" value
 * @method string  getBairro()      Returns the current record's "bairro" value
 * @method string  getCep()         Returns the current record's "cep" value
 * @method string  getComplemento() Returns the current record's "complemento" value
 * @method Erps    setCodErps()     Sets the current record's "cod_erps" value
 * @method Erps    setNome()        Sets the current record's "nome" value
 * @method Erps    setRg()          Sets the current record's "rg" value
 * @method Erps    setCpf()         Sets the current record's "cpf" value
 * @method Erps    setEmail()       Sets the current record's "email" value
 * @method Erps    setStatus()      Sets the current record's "status" value
 * @method Erps    setEstado()      Sets the current record's "estado" value
 * @method Erps    setCidade()      Sets the current record's "cidade" value
 * @method Erps    setRua()         Sets the current record's "rua" value
 * @method Erps    setNumero()      Sets the current record's "numero" value
 * @method Erps    setBairro()      Sets the current record's "bairro" value
 * @method Erps    setCep()         Sets the current record's "cep" value
 * @method Erps    setComplemento() Sets the current record's "complemento" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseErps extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('erps');
        $this->hasColumn('cod_erps', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nome', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('rg', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cpf', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('status', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('estado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cidade', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('rua', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('numero', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('bairro', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cep', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('complemento', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}