<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Agenda', 'bd');

/**
 * BaseAgenda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idagenda
 * @property string $nome
 * @property string $telefone
 * @property string $placa
 * @property string $modelo
 * @property string $horario_status
 * @property date $data_cadastro
 * 
 * @method integer getIdagenda()       Returns the current record's "idagenda" value
 * @method string  getNome()           Returns the current record's "nome" value
 * @method string  getTelefone()       Returns the current record's "telefone" value
 * @method string  getPlaca()          Returns the current record's "placa" value
 * @method string  getModelo()         Returns the current record's "modelo" value
 * @method string  getHorarioStatus()  Returns the current record's "horario_status" value
 * @method date    getDataCadastro()   Returns the current record's "data_cadastro" value
 * @method Agenda  setIdagenda()       Sets the current record's "idagenda" value
 * @method Agenda  setNome()           Sets the current record's "nome" value
 * @method Agenda  setTelefone()       Sets the current record's "telefone" value
 * @method Agenda  setPlaca()          Sets the current record's "placa" value
 * @method Agenda  setModelo()         Sets the current record's "modelo" value
 * @method Agenda  setHorarioStatus()  Sets the current record's "horario_status" value
 * @method Agenda  setDataCadastro()   Sets the current record's "data_cadastro" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgenda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agenda');
        $this->hasColumn('idagenda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nome', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('telefone', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('placa', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('modelo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('horario_status', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('data_cadastro', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}