<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ValorReparo', 'bd');

/**
 * BaseValorReparo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idvalor_reparo
 * @property float $valor
 * @property string $pecas_veiculo
 * @property string $modelo
 * @property Doctrine_Collection $Reparo
 * 
 * @method integer             getIdvalorReparo()  Returns the current record's "idvalor_reparo" value
 * @method float               getValor()          Returns the current record's "valor" value
 * @method string              getPecasVeiculo()   Returns the current record's "pecas_veiculo" value
 * @method string              getModelo()         Returns the current record's "modelo" value
 * @method Doctrine_Collection getReparo()         Returns the current record's "Reparo" collection
 * @method ValorReparo         setIdvalorReparo()  Sets the current record's "idvalor_reparo" value
 * @method ValorReparo         setValor()          Sets the current record's "valor" value
 * @method ValorReparo         setPecasVeiculo()   Sets the current record's "pecas_veiculo" value
 * @method ValorReparo         setModelo()         Sets the current record's "modelo" value
 * @method ValorReparo         setReparo()         Sets the current record's "Reparo" collection
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseValorReparo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('valor_reparo');
        $this->hasColumn('idvalor_reparo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('valor', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('pecas_veiculo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('modelo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reparo', array(
             'local' => 'idvalor_reparo',
             'foreign' => 'valor_reparo_idvalor_reparo'));
    }
}