<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OsServicos', 'erp');

/**
 * BaseOsServicos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_servico
 * @property float $valor
 * @property string $status
 * @property string $servico
 * @property float $tempo_padrao
 * @property float $tempo_pago
 * @property float $tempo_trabalhado
 * @property integer $cod_mecanico
 * @property integer $numero_os
 * @property Mecanico $Mecanico
 * @property Os $Os
 * 
 * @method integer    getCodServico()       Returns the current record's "cod_servico" value
 * @method float      getValor()            Returns the current record's "valor" value
 * @method string     getStatus()           Returns the current record's "status" value
 * @method string     getServico()          Returns the current record's "servico" value
 * @method float      getTempoPadrao()      Returns the current record's "tempo_padrao" value
 * @method float      getTempoPago()        Returns the current record's "tempo_pago" value
 * @method float      getTempoTrabalhado()  Returns the current record's "tempo_trabalhado" value
 * @method integer    getCodMecanico()      Returns the current record's "cod_mecanico" value
 * @method integer    getNumeroOs()         Returns the current record's "numero_os" value
 * @method Mecanico   getMecanico()         Returns the current record's "Mecanico" value
 * @method Os         getOs()               Returns the current record's "Os" value
 * @method OsServicos setCodServico()       Sets the current record's "cod_servico" value
 * @method OsServicos setValor()            Sets the current record's "valor" value
 * @method OsServicos setStatus()           Sets the current record's "status" value
 * @method OsServicos setServico()          Sets the current record's "servico" value
 * @method OsServicos setTempoPadrao()      Sets the current record's "tempo_padrao" value
 * @method OsServicos setTempoPago()        Sets the current record's "tempo_pago" value
 * @method OsServicos setTempoTrabalhado()  Sets the current record's "tempo_trabalhado" value
 * @method OsServicos setCodMecanico()      Sets the current record's "cod_mecanico" value
 * @method OsServicos setNumeroOs()         Sets the current record's "numero_os" value
 * @method OsServicos setMecanico()         Sets the current record's "Mecanico" value
 * @method OsServicos setOs()               Sets the current record's "Os" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOsServicos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('os_servicos');
        $this->hasColumn('cod_servico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valor', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('servico', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('tempo_padrao', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('tempo_pago', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('tempo_trabalhado', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('cod_mecanico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_os', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mecanico', array(
             'local' => 'cod_mecanico',
             'foreign' => 'cod_mecanico'));

        $this->hasOne('Os', array(
             'local' => 'numero_os',
             'foreign' => 'numero_os'));
    }
}