<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Imagens', 'bd');

/**
 * BaseImagens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idimagens
 * @property string $endereco_imagens
 * @property Doctrine_Collection $Mensagem
 * @property Doctrine_Collection $Reparo
 * 
 * @method integer             getIdimagens()        Returns the current record's "idimagens" value
 * @method string              getEnderecoImagens()  Returns the current record's "endereco_imagens" value
 * @method Doctrine_Collection getMensagem()         Returns the current record's "Mensagem" collection
 * @method Doctrine_Collection getReparo()           Returns the current record's "Reparo" collection
 * @method Imagens             setIdimagens()        Sets the current record's "idimagens" value
 * @method Imagens             setEnderecoImagens()  Sets the current record's "endereco_imagens" value
 * @method Imagens             setMensagem()         Sets the current record's "Mensagem" collection
 * @method Imagens             setReparo()           Sets the current record's "Reparo" collection
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImagens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imagens');
        $this->hasColumn('idimagens', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('endereco_imagens', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mensagem', array(
             'local' => 'idimagens',
             'foreign' => 'cod_imagem'));

        $this->hasMany('Reparo', array(
             'local' => 'idimagens',
             'foreign' => 'cod_imagem'));
    }
}