<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Noticia', 'bd');

/**
 * BaseNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_noticia
 * @property string $titulo_noticia
 * @property string $noticia
 * @property date $data_publicacao
 * @property string $endereco_imagem
 * 
 * @method integer getCodNoticia()      Returns the current record's "cod_noticia" value
 * @method string  getTituloNoticia()   Returns the current record's "titulo_noticia" value
 * @method string  getNoticia()         Returns the current record's "noticia" value
 * @method date    getDataPublicacao()  Returns the current record's "data_publicacao" value
 * @method string  getEnderecoImagem()  Returns the current record's "endereco_imagem" value
 * @method Noticia setCodNoticia()      Sets the current record's "cod_noticia" value
 * @method Noticia setTituloNoticia()   Sets the current record's "titulo_noticia" value
 * @method Noticia setNoticia()         Sets the current record's "noticia" value
 * @method Noticia setDataPublicacao()  Sets the current record's "data_publicacao" value
 * @method Noticia setEnderecoImagem()  Sets the current record's "endereco_imagem" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticia');
        $this->hasColumn('cod_noticia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('titulo_noticia', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('noticia', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('data_publicacao', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('endereco_imagem', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}