<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vendas', 'erp');

/**
 * BaseVendas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_venda
 * @property date $data_venda
 * @property float $valor_venda
 * @property integer $cod_cliente
 * @property integer $cod_item
 * @property Clientes $Clientes
 * @property Item $Item
 * 
 * @method integer  getCodVenda()    Returns the current record's "cod_venda" value
 * @method date     getDataVenda()   Returns the current record's "data_venda" value
 * @method float    getValorVenda()  Returns the current record's "valor_venda" value
 * @method integer  getCodCliente()  Returns the current record's "cod_cliente" value
 * @method integer  getCodItem()     Returns the current record's "cod_item" value
 * @method Clientes getClientes()    Returns the current record's "Clientes" value
 * @method Item     getItem()        Returns the current record's "Item" value
 * @method Vendas   setCodVenda()    Sets the current record's "cod_venda" value
 * @method Vendas   setDataVenda()   Sets the current record's "data_venda" value
 * @method Vendas   setValorVenda()  Sets the current record's "valor_venda" value
 * @method Vendas   setCodCliente()  Sets the current record's "cod_cliente" value
 * @method Vendas   setCodItem()     Sets the current record's "cod_item" value
 * @method Vendas   setClientes()    Sets the current record's "Clientes" value
 * @method Vendas   setItem()        Sets the current record's "Item" value
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendas');
        $this->hasColumn('cod_venda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('data_venda', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('valor_venda', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('cod_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cod_item', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clientes', array(
             'local' => 'cod_cliente',
             'foreign' => 'cod_clientes'));

        $this->hasOne('Item', array(
             'local' => 'cod_item',
             'foreign' => 'cod_item'));
    }
}