<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Veiculo', 'erp');

/**
 * BaseVeiculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_veiculo
 * @property string $placa
 * @property string $chassi
 * @property string $marca
 * @property string $modelo
 * @property string $cor
 * @property integer $ano
 * @property Doctrine_Collection $Email
 * @property Doctrine_Collection $Os
 * 
 * @method integer             getCodVeiculo()  Returns the current record's "cod_veiculo" value
 * @method string              getPlaca()       Returns the current record's "placa" value
 * @method string              getChassi()      Returns the current record's "chassi" value
 * @method string              getMarca()       Returns the current record's "marca" value
 * @method string              getModelo()      Returns the current record's "modelo" value
 * @method string              getCor()         Returns the current record's "cor" value
 * @method integer             getAno()         Returns the current record's "ano" value
 * @method Doctrine_Collection getEmail()       Returns the current record's "Email" collection
 * @method Doctrine_Collection getOs()          Returns the current record's "Os" collection
 * @method Veiculo             setCodVeiculo()  Sets the current record's "cod_veiculo" value
 * @method Veiculo             setPlaca()       Sets the current record's "placa" value
 * @method Veiculo             setChassi()      Sets the current record's "chassi" value
 * @method Veiculo             setMarca()       Sets the current record's "marca" value
 * @method Veiculo             setModelo()      Sets the current record's "modelo" value
 * @method Veiculo             setCor()         Sets the current record's "cor" value
 * @method Veiculo             setAno()         Sets the current record's "ano" value
 * @method Veiculo             setEmail()       Sets the current record's "Email" collection
 * @method Veiculo             setOs()          Sets the current record's "Os" collection
 * 
 * @package    tcc
 * @subpackage model
 * @author     Renato e Leo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVeiculo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('veiculo');
        $this->hasColumn('cod_veiculo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('placa', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('chassi', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('marca', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('modelo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cor', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Email', array(
             'local' => 'cod_veiculo',
             'foreign' => 'cod_veiculo'));

        $this->hasMany('Os', array(
             'local' => 'cod_veiculo',
             'foreign' => 'cod_veiculo'));
    }
}