<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/10/07 22:33:37

return array(
'erp' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=erp',
  'username' => 'root',
  'password' => NULL,
  'name' => 'erp',
)),

'bd' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bd',
  'username' => 'root',
  'password' => NULL,
  'name' => 'bd',
)),);
