<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/07 23:04:48
sfConfig::add(array(
  'mod_aniversariante_enabled' => true,
  'mod_aniversariante_view_class' => 'sfPHP',
));
