<?php

/**
 * AcessosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcessosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcessosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Acessos');
    }
}