<?php

/**
 * ErpsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ErpsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ErpsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Erps');
    }
}