<?php

/**
 * FuncaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Funcao');
    }
}