<?php

/**
 * MaterialApoioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialApoioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialApoioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialApoio');
    }
}