<?php

/**
 * MecanicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MecanicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MecanicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mecanico');
    }
}