<?php

/**
 * MetasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Metas');
    }
}