<?php

/**
 * OsServicosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OsServicosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OsServicosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OsServicos');
    }
}