<?php

/**
 * ReparoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReparoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReparoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reparo');
    }
}