<?php

/**
 * ValorReparoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValorReparoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValorReparoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValorReparo');
    }
}