<?php

/**
 * VeiculoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VeiculoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VeiculoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Veiculo');
    }
}