<?php

/**
 * VendasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VendasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vendas');
    }
}